### ISSUE TITLE
repeat creating

### ISSUE THREAD

**Issue by spring520** [youmi-zym/GO-SLAM#19]
I tried following command to evaluate the model on Replica
```bash
./evaluate_on_replica.sh rgbd first_try

python run.py configs/Replica/office1.yaml –device cuda:3 –mode rgbd –output ./logs/office1/exp1
```

my config file looks like
```yaml
inherit_from: configs/Replica/replica.yaml
mode: rgbd
mapping: bound: [[-5.0, 5.0], [-5.0, 5.0], [-5.0, 5.0]]
meshing:
  gt_mesh_path: /remote-home/usr/16-GO-SLAM/datasets/Replica/office1_mesh.ply
data:
  input_folder: /remote-home/usr/16-GO-SLAM/datasets/Replica/office1
  output: /home/yzhang/exps/goslam/Replica/office1/rgbd
```

but it turns out that the coding is tring to create directory repeatedly and the usage of GPU and CPU is pretty so I think something is wrong here. the directory under ./logs looks like "/remote-home/usr/16-GO-SLAM/logs/office1/exp1/code/logs/office1/exp1/code/logs/office1/exp1/code/logs/office1/exp1/code/logs/office1/exp1/code/logs/office1/exp1/code/logs/office1/exp1/code/logs/office1/exp1/code/"
