### ISSUE TITLE
About the mesh on custom dataset

### ISSUE THREAD

**Issue by Zhaohuai-L** [youmi-zym/GO-SLAM#22]
Hi,
thanks for the amazing work.

I followed the instructions in issue #4 to adapt GO-SLAM to the custom KITTI RGB-D dataset. To get the mesh, I use the same code as in the evaluation to generate it as follows,
![image](https://github.com/youmi-zym/GO-SLAM/assets/62138387/82560376-983f-4362-8e28-515287d99241)
However, the generated mesh is quite different from the genrated point cloud, so may i ask if there something wrong with me ?

![pointcloud](https://github.com/youmi-zym/GO-SLAM/assets/62138387/ce7e13c6-1ad5-4065-a164-5c47c455745f)
![mesh](https://github.com/youmi-zym/GO-SLAM/assets/62138387/b77e0b59-e4e3-4bde-8818-a2b7ef35649a)

The configuration parameters I used are as follows,
```
mapping:
  device: "cuda:0"
  bound: [[-100, 100], [-100, 100], [-10, 10]]      #for custom kitti
rendering:
  N_samples: 24
  N_surface: 48

meshing:
  eval_rec: False
  resolution: 1024  # change to 2048 for higher resolution geometry
  get_largest_components: False
  remove_small_geometry_threshold: 0.2
  n_points_to_eval: 200000
  mesh_threshold_to_eval: 0.05
  forecast_radius: 25

cam:  #intrinsic is different per scene in TUM
  H: 376 
  W: 1241 
  fx: 718.8560180664062
  fy: 718.8560180664062
  cx: 607.1928100585938
  cy: 185.2156982421875
  H_edge: 0
  W_edge: 0
  H_out: 240        
  W_out: 1224
  H_top_edge: 136   # for custom kitti
```
Best
